### ISSUE TITLE
Make the app work with docker-compose up: npm ERR! missing script: build

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/Workflow-App#9]
Step 6/9 : COPY ./ /opt/app/
 ---> d6fa1774e812
Step 7/9 : RUN npm run build
 ---> Running in b8d4d76385d0
npm ERR! Linux 4.9.60-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.13.1
npm ERR! npm  v3.10.10

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app/npm-debug.log
ERROR: Service 'workflow-app' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 1

**Comment by Kuhno92** [comment]
done 1ab76bdd7d083407338cc8f8eb5bb3787f3a2753

**Comment by frostyandy2k** [comment]
Not yet

```
Successfully built f1628e8f9817
Successfully tagged workflow_workflow-app:latest
WARNING: Image for service workflow-app was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating workflow_workflow-app_1 ... done
Attaching to workflow_workflow-app_1
workflow-app_1  | module.js:549
workflow-app_1  |     throw err;
workflow-app_1  |     ^
workflow-app_1  | 
workflow-app_1  | Error: Cannot find module 'mongoose'
workflow-app_1  |     at Function.Module._resolveFilename (module.js:547:15)
```

**Comment by Kuhno92** [comment]
next try ;) 
image shrink to 146mb
c6797832a79dac4285206152f3af0a8e364cd2fa

**Comment by frostyandy2k** [comment]
good to go
